/* DO STATUS */
const DO_STATUS = {
    CREATE_DO: "CREATE_DO",
    PENDING_ISSUE: "PENDING_ISSUE",
    PENDING_RECEIPT: "PENDING_RECEIPT",
    DELIVERED: "DELIVERED",
    NOT_ISSUED: "NOT_ISSUED",
    PARTIALLY_ISSUED: "PARTIALLY_ISSUED",
    PARTIALLY_DELIVERED: "PARTIALLY_DELIVERED",
    FULLY_ISSUED: "FULLY_ISSUED"
};
const DO_ROLE = {
    VIEWER: "VIEWER",
    CREATOR: "CREATOR",
    APPROVER: "APPROVER"
};
const DO_FE_STATUS = {
    CREATE_DO: "CREATE DO",
    PENDING_ISSUE: "PENDING ISSUE",
    PENDING_RECEIPT: "PENDING RECEIPT",
    DELIVERED: "DELIVERED",
    NOT_ISSUED: "NOT ISSUED",
    PARTIALLY_ISSUED: "PARTIALLY ISSUED",
    FULLY_ISSUED: "FULLY ISSUED",
    PARTIALLY_DELIVERED: "PARTIALLY DELIVERED"
};
Object.freeze(DO_STATUS);
Object.freeze(DO_FE_STATUS);
Object.freeze(DO_ROLE);

export { DO_STATUS, DO_FE_STATUS, DO_ROLE };
